on:
  push:

jobs:
  molecule-test:
    runs-on: ubuntu-latest
    container: potyarkin/cirrus-run
    steps:
      - uses: actions/checkout@v2
      - run: cirrus-run .ci/cirrus.yml.j2
        env:
          CIRRUS_API_TOKEN: ${{ secrets.CIRRUS_API_TOKEN }}
          CIRRUS_GITHUB_REPO: sio/.cirrus-ci-jobs
          CIRRUS_SHOW_BUILD_LOG: always
